### ISSUE TITLE
Checking any recipe in NEI causes a crash

### ISSUE THREAD

**Issue by Parapetenia** [JadedPacks/Magic-Farm-3#2]
* Steps to Reproduce
1. Open the GUI for a Tinkers Crafting Station(I didn't check other crafting methods)
2. Click on any item or block listed in NEI.
3. Minecraft will crash to desktop.

* Crash Log:
https://pastebin.pl/view/f60b2a2a

* Modpack Version:
Current version downloaded from the Twitch Launcher on 17 Sept. 2020, Version 11.36
* Server/LAN/Single Player:
Single Player
* Java: 
1.8.0.251

**Comment by remclave** [comment]
Confirmed. Version 1.1.36 is unstable. We are still trying to figure out what is causing to crash. This version was put together by our lead developer "Kris" who is no longer with us. Tecrogue and I, Remclave, are now the team devs. 

If you still wish to play Magic Farm 3, please download and install version 1.1.35. It still works correctly.

**Comment by remclave** [comment]
The problem has been corrected and will be made available on the next release.

**Comment by Parapetenia** [comment]
Thank you for the replies, and sounds good.
